# Generated by Django 4.1.5 on 2023-01-19 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 1, 19, 6, 39, 47, 497770, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
