# Generated by Django 4.1.5 on 2023-01-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0003_response_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
